# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_PATH: ConatinerAppRevision/ConatinerAppRevision.csproj
  ZIP_PATH: WpfApp6/bin/Release/net5.0-windows/win-x86/publish/WpfApp6-Portable.zip
  EXE_PATH: WpfApp6/bin/Release/net5.0-windows/win-x86/publish/WpfApp6.exe
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Release Publish
      run: dotnet publish -c Release -o ./publish
    - name: Create Zip File from publish
      run: zip -r deploy.zip ./publish
    - name: Upload to Release Action
      # You may pin to the exact commit or the version.
      # uses: Shopify/upload-to-release@c77c9b3e5d288adaef98a7007bf92340ec6ce03b
      uses: Shopify/upload-to-release@v2.0.0
      with:
        # Artifact name
        name: abc
        # Path to the file to upload
        path: ./publish/deploy.zip
        # Content type for the file
        content-type: application/octet-stream
        # secrets.GITHUB_TOKEN
        repo-token: 
