name: Trigger auto deployment for shuklacontapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/shuklacontapp-AutoDeployTrigger-f4ce55ee-6868-4dc1-8e94-8240e5f4b8a2.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SHUKLACONTAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: cae808cbe785acr.azurecr.io
          registryUsername: ${{ secrets.SHUKLACONTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SHUKLACONTAPP_REGISTRY_PASSWORD }}
          containerAppName: shuklacontapp
          resourceGroup: RG0
          imageToBuild: cae808cbe785acr.azurecr.io/shuklacontapp:${{ github.sha }}
          
            

     

